{
 "title": "Codefresh / Pipeline Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "pipeline_id", "label": "Pipeline ID" }
  ]
 },
 "panels": [
  {
   "title": "Volume Allocation",
   "type": "graph",
   "description": "Shows Kubernetes PVC allocation",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_labels{label_pipeline_id=\"$pipeline_id\",label_codefresh_app=\"dind\"} * on(persistentvolumeclaim) kube_persistentvolumeclaim_resource_requests_storage_bytes\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_labels{label_pipeline_id=\"$pipeline_id\",label_codefresh_app=\"dind\"} * on(persistentvolumeclaim) kube_persistentvolumeclaim_resource_requests_storage_bytes)",
     "legendFormat": "All volumes"
    }
   ]
  },
  {
   "title": "Volume Stats",
   "type": "graph",
   "description": "Shows PVC disk stats. For local PVs, this will show filesystem stats of the whole local disk of the Kubernetes node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg (\n(kube_persistentvolumeclaim_labels{label_pipeline_id=\"$pipeline_id\",label_codefresh_app=\"dind\"} * on(persistentvolumeclaim) group_right() kubelet_volume_stats_capacity_bytes)\n  -\n(kube_persistentvolumeclaim_labels{label_pipeline_id=\"$pipeline_id\",label_codefresh_app=\"dind\"} * on(persistentvolumeclaim) group_right() kubelet_volume_stats_available_bytes)\n) by (persistentvolumeclaim)\n",
     "legendFormat": "Usage: {{persistentvolumeclaim}}"
    },
    {
     "expr": "avg(kube_persistentvolumeclaim_labels{label_pipeline_id=\"$pipeline_id\",label_codefresh_app=\"dind\"} * on(persistentvolumeclaim) group_right() kubelet_volume_stats_capacity_bytes) by (persistentvolumeclaim)\n",
     "legendFormat": "Capacity: {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Dind Pod CPU Allocation",
   "type": "graph",
   "description": "Shows Kubernetes CPU requests/limits",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_labels{label_io_codefresh_pipelineId=\"$pipeline_id\"} * on (pod) kube_pod_container_resource_limits_cpu_cores{pod=~\"dind-[a-f0-9]{24}\"}",
     "legendFormat": "CPU Limit {{pod}}"
    },
    {
     "expr": "sum(kube_pod_labels{label_io_codefresh_pipelineId=\"$pipeline_id\"} * on (pod) kube_pod_container_resource_limits_cpu_cores{pod=~\"dind-[a-f0-9]{24}\"})",
     "legendFormat": "Total CPU Limits"
    },
    {
     "expr": "kube_pod_labels{label_io_codefresh_pipelineId=\"$pipeline_id\"} * on (pod) kube_pod_container_resource_requests_cpu_cores{pod=~\"dind-[a-f0-9]{24}\"}",
     "legendFormat": "CPU Request {{pod}}"
    },
    {
     "expr": "sum(kube_pod_labels{label_io_codefresh_pipelineId=\"$pipeline_id\"} * on (pod) kube_pod_container_resource_requests_cpu_cores{pod=~\"dind-[a-f0-9]{24}\"})",
     "legendFormat": "Total CPU Requests"
    }
   ]
  },
  {
   "title": "Dind Pod Memory Allocation",
   "type": "graph",
   "description": "Shows Kubernetes memory requests/limits",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_labels{label_io_codefresh_pipelineId=\"$pipeline_id\"} * on (pod) kube_pod_container_resource_limits_memory_bytes{pod=~\"dind-[a-f0-9]{24}\"}",
     "legendFormat": "Memory limit {{pod}}"
    },
    {
     "expr": "sum(kube_pod_labels{label_io_codefresh_pipelineId=\"$pipeline_id\"} * on (pod) kube_pod_container_resource_limits_memory_bytes{pod=~\"dind-[a-f0-9]{24}\"})",
     "legendFormat": "Total memory limits"
    },
    {
     "expr": "kube_pod_labels{label_io_codefresh_pipelineId=\"$pipeline_id\"} * on (pod) kube_pod_container_resource_requests_memory_bytes{pod=~\"dind-[a-f0-9]{24}\"}",
     "legendFormat": "Memory request {{pod}}"
    },
    {
     "expr": "sum(kube_pod_labels{label_io_codefresh_pipelineId=\"$pipeline_id\"} * on (pod) kube_pod_container_resource_requests_memory_bytes{pod=~\"dind-[a-f0-9]{24}\"})",
     "legendFormat": "Total memory requests"
    }
   ]
  },
  {
   "title": "Dind Container Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "avg(rate( (kube_pod_labels{label_io_codefresh_pipelineId=\"$pipeline_id\"} * on (pod) group_right() container_network_receive_bytes_total{pod=~\"dind-[a-f0-9]{24}\"})[100s:])) by (pod) * 8 / 1000000",
     "legendFormat": "Network Receive Mbit/s"
    },
    {
     "expr": "avg(rate( (kube_pod_labels{label_io_codefresh_pipelineId=\"$pipeline_id\"} * on (pod) group_right() container_network_transmit_bytes_total{pod=~\"dind-[a-f0-9]{24}\"})[100s:])) by (pod) * 8 / 1000000",
     "legendFormat": "Network Transmit Mbit/s"
    }
   ]
  }
 ]
}