{
 "title": "Codefresh / Build Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "build_id", "label": "Build ID" }
  ]
 },
 "panels": [
  {
   "title": "Volume Allocation",
   "type": "graph",
   "description": "Shows Kubernetes PVC allocation",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_labels{label_pod_name=\"dind-$build_id\"} * on(persistentvolumeclaim) kube_persistentvolumeclaim_resource_requests_storage_bytes\n",
     "legendFormat": "{{persistentvolume}}"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_labels{label_pod_name=\"dind-$build_id\"} * on(persistentvolumeclaim) kube_persistentvolumeclaim_resource_requests_storage_bytes)",
     "legendFormat": "All volumes"
    }
   ]
  },
  {
   "title": "Volume Stats",
   "type": "graph",
   "description": "Shows PVC disk stats. For local PVs, this will show filesystem stats of the whole local disk of the Kubernetes node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(\nkubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"pvc-dind-$build_id\"}\n  -\nkubelet_volume_stats_available_bytes{persistentvolumeclaim=\"pvc-dind-$build_id\"}\n) by (persistentvolumeclaim)\n",
     "legendFormat": "Volume Usage {{persistentvolumeclaim}}"
    },
    {
     "expr": "avg(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"pvc-dind-$build_id\"}) by (persistentvolumeclaim)\n",
     "legendFormat": "Volume Capacity {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Dind Container CPU Usage",
   "type": "graph",
   "description": "Shows CPU usage in CPU units",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=\"dind-$build_id\",container=\"dind\"}[40s])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Dind Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{pod=\"dind-$build_id\",container=\"dind\"}) by (pod) / 1000000000",
     "legendFormat": "Memory usage (GB) {{pod}}"
    },
    {
     "expr": "avg(container_spec_memory_limit_bytes{pod=\"dind-$build_id\",container=\"dind\"}) by (pod) / 1000000000",
     "legendFormat": "Memory limit (GB) {{pod}}"
    }
   ]
  },
  {
   "title": "Dind Container Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_network_receive_bytes_total{pod=\"dind-$build_id\"}[100s])) by (pod) * 8 / 1000000",
     "legendFormat": "Network Receive {{pod}}"
    },
    {
     "expr": "avg(rate(container_network_transmit_bytes_total{pod=\"dind-$build_id\"}[100s])) by (pod) * 8 / 1000000",
     "legendFormat": "Network Transmit {{pod}}"
    }
   ]
  }
 ]
}